name: Deploy Vite App to GitHub Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🧱 Checkout code
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci

      # 👇 动态计算部署 base 路径
      - name: 🔧 Set VITE_BASE for GitHub Pages
        run: |
          # 格式: /<repo>/
          REPO_NAME="${{ github.event.repository.name }}"
          VITE_BASE="/$REPO_NAME/"
          echo "VITE_BASE=$VITE_BASE" >> .env.production
          echo "Using base path: $VITE_BASE"

      - name: 🛠️ Build project
        run: npm run build

      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true
          commit_message: '🚀 Deploy Vite app from ${{ github.sha }}'
