name: Deploy Vite App to GitHub Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🧱 Checkout code
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci

      # 👇 动态计算完整的部署 URL
      - name: 🔧 Set VITE_BASE (Full URL)
        run: |
          OWNER="${{ github.repository_owner }}"
          REPO_NAME="${{ github.event.repository.name }}"

          # 构造完整 URL: https://<owner>.github.io/<repo>/
          VITE_BASE="https://$OWNER.github.io/$REPO_NAME/"

          echo "VITE_BASE=$VITE_BASE" >> .env.production
          echo "Deploy base URL: $VITE_BASE"

      - name: 🛠️ Build project
        run: npm run build

      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true
          commit_message: '🚀 Deploy Vite app from ${{ github.sha }}'
